# Generated by Django 5.2.4 on 2025-09-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doctor_opinion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
